from pygame import Surface, image, transform
from vehicle import Vehicle
import numpy as np
from utils import R2D, N2S, N2S2D, D2L

# TODO: Add comments and descriptions
# TODO: Make maps that are autogenerated
#       Some ground rules:
#           - The map is always the same size
#           - The px/m scale is always the same
#           - The quay can vary in size
#           - The quay must be at the edges of the map
#           - The bounds are always at the edges of the map
# TODO: Add static obstacles that the boat has to dock in between,
#       use a new grey version of Target() for this
# TODO: Change colliding edge to be determined by which edge is closed to the center of the map
# TODO: Define all maps and obstacles in {n} then scale them
# TODO: Change target to take in a vehicle object


class Map():
    # Map parameters
    MAX_BOX_WIDTH = 900     # [px]  Max overall box width
    MAX_BOX_HEIGHT = 800    # [px]  Max overall box height
    WALL_THICKNESS = 2  # [m]   Border wall thickness
    # Size of map (north, east), must be overwritten
    MAP_SIZE = None  # [m]

    def __init__(self, map_size, convex_set: list = None) -> None:
        self.convex_set = convex_set
        self.MAP_SIZE = map_size
        self._init_box()

    def _init_box(self):
        """
        Initialize box

        """

        BOX_WIDTH = self.MAX_BOX_WIDTH      # [px]
        BOX_HEIGHT = self.MAX_BOX_HEIGHT    # [px]

        map_width = self.MAP_SIZE[1]    # [m] east
        map_height = self.MAP_SIZE[0]   # [m] north

        box_ratio = self.MAX_BOX_WIDTH / self.MAX_BOX_HEIGHT
        map_ratio = map_width / map_height

        if box_ratio > map_ratio:
            scale = BOX_HEIGHT/map_height
            BOX_WIDTH = map_width*scale
        else:
            scale = BOX_WIDTH/map_width
            BOX_HEIGHT = map_height*scale

        self.origin = np.array([BOX_WIDTH/2, BOX_HEIGHT/2, 0], float)

        # Make global
        self.scale = scale
        self.BOX_WIDTH = BOX_WIDTH
        self.BOX_HEIGHT = BOX_HEIGHT


class Target():
    def __init__(self, eta_d: np.ndarray, vehicle: Vehicle, map: Map) -> None:
        """
        Displays and holds target pose properties

        Parameters
        ----------
        eta_d : np.ndarray
            Is the desired pose in {n} frame
        vehicle : Vehicle
            The vehicle object that will be passed to the simulator
        scale: float
            Scaling to fit screen   [px/m]
        map_origin: float
            x, y distance from top left corner to the center
            of the game screen

        Attributes
        ----------
        image : pygame.image
            Visualisation of target pose
        rect : pygame.Rect
            Hitbox of the target pose
        eta_d : np.ndarray
            Desired pose in {n} frame
        """
        scale = map.scale
        L = vehicle.L
        B = vehicle.B

        # Use screen coordinates for rendering
        eta_ds = N2S(eta_d, scale, map.origin)
        target_image = image.load(
            'vehicle/images/target.png')
        target_image = transform.scale(
            target_image, (scale*B, scale*L))
        self.image = transform.rotate(
            target_image, -R2D(eta_ds[-1]))

        center = (eta_ds[0], eta_ds[1])
        self.rect = self.image.get_rect(center=center)
        self.eta_d = eta_d.copy()  # Save desired pose
